[naverpost_cine21_review]
title = "씨네21 ─ 20자평"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=520134&memberNo=15205863"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_cine21_news]
title = "씨네21 ─ 국내뉴스"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=450865&memberNo=15205863"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_cine21_view]
title = "씨네21 ─ 알고봅시다"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=269621&memberNo=15205863"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_cine21_feature]
title = "씨네21 ─ feature"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=229028&memberNo=15205863"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_cine21_whoareyou]
title = "씨네21 ─ Who are you"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=371914&memberNo=15205863"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_cine21_foreignnews]
title = "씨네21 ─ 해외뉴스"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=452114&memberNo=15205863"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_cine21_coverstar]
title = "씨네21 ─ 커버스타"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=228138&memberNo=15205863"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_cine21_interview]
title = "씨네21 ─ 인터뷰"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=229029&memberNo=15205863"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[article]
title = "씨네21 ─ 기사 ─ 전체"
url = "http://www.cine21.com/news/list/"
entrySelector = "ul.news li:not(:nth-child(5))"
titleSelector = "span.tit"
linkSelector = "a"
contentSelector = "span.nothumb"
imageSelector = "span.thumb img.thumb_img"
waitUntil = "networkidle"
onFail = "stale"

[article_news]
title = "씨네21 ─ 기사 ─ 뉴스"
url = "http://www.cine21.com/news/list/?idx=1"
entrySelector = "ul.news li:not(:nth-child(5))"
titleSelector = "span.tit"
linkSelector = "a"
contentSelector = "span.nothumb"
imageSelector = "span.thumb img.thumb_img"
waitUntil = "networkidle"
onFail = "stale"

[article_planning]
title = "씨네21 ─ 기사 ─ 기획"
url = "http://www.cine21.com/news/list/?idx=2"
entrySelector = "ul.news li:not(:nth-child(5))"
titleSelector = "span.tit"
linkSelector = "a"
contentSelector = "span.nothumb"
imageSelector = "span.thumb img.thumb_img"
waitUntil = "networkidle"
onFail = "stale"

[article_review]
title = "씨네21 ─ 기사 ─ 기획"
url = "http://www.cine21.com/news/list/?idx=3"
entrySelector = "ul.news li:not(:nth-child(5))"
titleSelector = "span.tit"
linkSelector = "a"
contentSelector = "span.nothumb"
imageSelector = "span.thumb img.thumb_img"
waitUntil = "networkidle"
onFail = "stale"

[article_interview]
title = "씨네21 ─ 기사 ─ 인터뷰"
url = "http://www.cine21.com/news/list/?idx=4"
entrySelector = "ul.news li:not(:nth-child(5))"
titleSelector = "span.tit"
linkSelector = "a"
contentSelector = "span.nothumb"
imageSelector = "span.thumb img.thumb_img"
waitUntil = "networkidle"
onFail = "stale"

[article_column]
title = "씨네21 ─ 기사 ─ 칼럼"
url = "http://www.cine21.com/news/list/?idx=5"
entrySelector = "ul.news li:not(:nth-child(5))"
titleSelector = "span.tit"
linkSelector = "a"
contentSelector = "span.nothumb"
imageSelector = "span.thumb img.thumb_img"
waitUntil = "networkidle"
onFail = "stale"

[article_critic]
title = "씨네21 ─ 기사 ─ 평론"
url = "http://www.cine21.com/news/list/?idx=6"
entrySelector = "ul.news li:not(:nth-child(5))"
titleSelector = "span.tit"
linkSelector = "a"
contentSelector = "span.nothumb"
imageSelector = "span.thumb img.thumb_img"
waitUntil = "networkidle"
onFail = "stale"

[article_culture]
title = "씨네21 ─ 기사 ─ 컬쳐"
url = "http://www.cine21.com/news/list/?idx=7"
entrySelector = "ul.news li:not(:nth-child(5))"
titleSelector = "span.tit"
linkSelector = "a"
contentSelector = "span.nothumb"
imageSelector = "span.thumb img.thumb_img"
waitUntil = "networkidle"
onFail = "stale"

[article_filmfest]
title = "씨네21 ─ 기사 ─ 영화제"
url = "http://www.cine21.com/news/list/?idx=8"
entrySelector = "ul.news li:not(:nth-child(5))"
titleSelector = "span.tit"
linkSelector = "a"
contentSelector = "span.nothumb"
imageSelector = "span.thumb img.thumb_img"
waitUntil = "networkidle"
onFail = "stale"

[dailynews]
title = "씨네21 ─ 데일리뉴스"
url = "http://www.cine21.com/news/issue/list"
entrySelector = "ul.news li:not(:nth-child(5))"
titleSelector = "span.tit"
linkSelector = "a"
contentSelector = "span.nothumb"
imageSelector = "span.thumb img.thumb_img"
waitUntil = "networkidle"
onFail = "stale"

[movie_playing]
title = "씨네21 ─ 영화 ─ 현재 상영중"
url = "http://www.cine21.com/movie/lists/playing"
entrySelector = "ul.mov_info_list li.mov_info_li"
titleSelector = "div.over span.tit"
linkSelector = "a"
contentSelector = "div.over span.open_date"
imageSelector = "a img.thumb"
waitUntil = "networkidle"
onFail = "stale"

[movie_coming_date]
title = "씨네21 ─ 영화 ─ 개봉일 확정"
url = "http://www.cine21.com/movie/lists/coming_date"
entrySelector = "ul.mov_info_list li.mov_info_li"
titleSelector = "div.over span.tit"
linkSelector = "a"
contentSelector = "div.over span.open_date"
imageSelector = "a img.thumb"
waitUntil = "networkidle"
onFail = "stale"

[movie_coming_month]
title = "씨네21 ─ 영화 ─ 개봉월 확정"
url = "http://www.cine21.com/movie/lists/coming_month"
entrySelector = "ul.mov_info_list li.mov_info_li"
titleSelector = "div.over span.tit"
linkSelector = "a"
contentSelector = "div.over span.open_date"
imageSelector = "a img.thumb"
waitUntil = "networkidle"
onFail = "stale"

[movie_yet]
title = "씨네21 ─ 영화 ─ 개봉 미정"
url = "http://www.cine21.com/movie/lists/yet"
entrySelector = "ul.mov_info_list li.mov_info_li"
titleSelector = "div.over span.tit"
linkSelector = "a"
contentSelector = "div.over"
imageSelector = "a img.thumb"
waitUntil = "networkidle"
onFail = "stale"

[navertv]
title = "씨네21 ─ 네이버TV"
url = "https://tv.naver.com/cine21/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"
